//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Necropsyology.Core.Recurso {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RecursoListadoNecros {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RecursoListadoNecros() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Necropsyology.Core.Recurso.RecursoListadoNecros", typeof(RecursoListadoNecros).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choices.
        /// </summary>
        public static string BtnAccion {
            get {
                return ResourceManager.GetString("BtnAccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Organization.
        /// </summary>
        public static string BtnNewOrg {
            get {
                return ResourceManager.GetString("BtnNewOrg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create general report.
        /// </summary>
        public static string BtnNewRepGral {
            get {
                return ResourceManager.GetString("BtnNewRepGral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create bovine report.
        /// </summary>
        public static string BtnNRepBov {
            get {
                return ResourceManager.GetString("BtnNRepBov", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string HColAccion {
            get {
                return ResourceManager.GetString("HColAccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to date.
        /// </summary>
        public static string HColFecha {
            get {
                return ResourceManager.GetString("HColFecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice.
        /// </summary>
        public static string HColFolio {
            get {
                return ResourceManager.GetString("HColFolio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animal identifier.
        /// </summary>
        public static string HColIdAnimal {
            get {
                return ResourceManager.GetString("HColIdAnimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization.
        /// </summary>
        public static string HColOrganizacion {
            get {
                return ResourceManager.GetString("HColOrganizacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of Necropsies.
        /// </summary>
        public static string TituloPagina {
            get {
                return ResourceManager.GetString("TituloPagina", resourceCulture);
            }
        }
    }
}
