//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Necropsyology.Core.Recurso {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RecursoNecropsia {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RecursoNecropsia() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Necropsyology.Core.Recurso.RecursoNecropsia", typeof(RecursoNecropsia).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Professional Certificate.
        /// </summary>
        public static string LblEtiCedMVZ {
            get {
                return ResourceManager.GetString("LblEtiCedMVZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Colour.
        /// </summary>
        public static string LblEtiColor {
            get {
                return ResourceManager.GetString("LblEtiColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Colour.
        /// </summary>
        public static string LblEtiColorEsq {
            get {
                return ResourceManager.GetString("LblEtiColorEsq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Body Condition.
        /// </summary>
        public static string LblEtiCond {
            get {
                return ResourceManager.GetString("LblEtiCond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clinical diagnosis.
        /// </summary>
        public static string LblEtiDiagnostico {
            get {
                return ResourceManager.GetString("LblEtiDiagnostico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sick Days.
        /// </summary>
        public static string LblEtiDiasEnfer {
            get {
                return ResourceManager.GetString("LblEtiDiasEnfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Address Organization.
        /// </summary>
        public static string LblEtiDomOrg {
            get {
                return ResourceManager.GetString("LblEtiDomOrg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Age.
        /// </summary>
        public static string LblEtiEdad {
            get {
                return ResourceManager.GetString("LblEtiEdad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edema.
        /// </summary>
        public static string LblEtiEdema {
            get {
                return ResourceManager.GetString("LblEtiEdema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email.
        /// </summary>
        public static string LblEtiEmailMVZ {
            get {
                return ResourceManager.GetString("LblEtiEmailMVZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Species.
        /// </summary>
        public static string LblEtiEspecie {
            get {
                return ResourceManager.GetString("LblEtiEspecie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Euthanasia.
        /// </summary>
        public static string LblEtiEut {
            get {
                return ResourceManager.GetString("LblEtiEut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Date.
        /// </summary>
        public static string LblEtiFecha {
            get {
                return ResourceManager.GetString("LblEtiFecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Date of Death.
        /// </summary>
        public static string LblEtiFecMue {
            get {
                return ResourceManager.GetString("LblEtiFecMue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invoice.
        /// </summary>
        public static string LblEtiFolio {
            get {
                return ResourceManager.GetString("LblEtiFolio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Animal History.
        /// </summary>
        public static string LblEtiHistoria {
            get {
                return ResourceManager.GetString("LblEtiHistoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Animal Id.
        /// </summary>
        public static string LblEtiIdAnimal {
            get {
                return ResourceManager.GetString("LblEtiIdAnimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Place of death.
        /// </summary>
        public static string LblEtiLugMue {
            get {
                return ResourceManager.GetString("LblEtiLugMue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email.
        /// </summary>
        public static string LblEtiMailOrg {
            get {
                return ResourceManager.GetString("LblEtiMailOrg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Name.
        /// </summary>
        public static string LblEtiNomMVZ {
            get {
                return ResourceManager.GetString("LblEtiNomMVZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Name.
        /// </summary>
        public static string LblEtiNomOrg {
            get {
                return ResourceManager.GetString("LblEtiNomOrg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Organization.
        /// </summary>
        public static string LblEtiOrg {
            get {
                return ResourceManager.GetString("LblEtiOrg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Weight.
        /// </summary>
        public static string LblEtiPeso {
            get {
                return ResourceManager.GetString("LblEtiPeso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Owner.
        /// </summary>
        public static string LblEtiPropOrg {
            get {
                return ResourceManager.GetString("LblEtiPropOrg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sex.
        /// </summary>
        public static string LblEtiSexo {
            get {
                return ResourceManager.GetString("LblEtiSexo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Signs.
        /// </summary>
        public static string LblEtiSignos {
            get {
                return ResourceManager.GetString("LblEtiSignos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Telephone.
        /// </summary>
        public static string LblEtiTelMVZ {
            get {
                return ResourceManager.GetString("LblEtiTelMVZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Organization Phone.
        /// </summary>
        public static string LblEtiTelOrg {
            get {
                return ResourceManager.GetString("LblEtiTelOrg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Treatment.
        /// </summary>
        public static string LblEtiTratamiento {
            get {
                return ResourceManager.GetString("LblEtiTratamiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a General Necropsy Report.
        /// </summary>
        public static string LblHeaderTitulo {
            get {
                return ResourceManager.GetString("LblHeaderTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Choose one.
        /// </summary>
        public static string LblItemSel {
            get {
                return ResourceManager.GetString("LblItemSel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Musculoskeletal System.
        /// </summary>
        public static string LblSubTitEsqueleto {
            get {
                return ResourceManager.GetString("LblSubTitEsqueleto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Organization Data.
        /// </summary>
        public static string LblTitDatGral {
            get {
                return ResourceManager.GetString("LblTitDatGral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Necropsy finding.
        /// </summary>
        public static string LblTitHallazgo {
            get {
                return ResourceManager.GetString("LblTitHallazgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Disease Background.
        /// </summary>
        public static string LblTitHistoria {
            get {
                return ResourceManager.GetString("LblTitHistoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MVZ information.
        /// </summary>
        public static string LblTitMVZ {
            get {
                return ResourceManager.GetString("LblTitMVZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Patient Information.
        /// </summary>
        public static string LblTitPaciente {
            get {
                return ResourceManager.GetString("LblTitPaciente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Indicate Color.
        /// </summary>
        public static string TxtPHColor {
            get {
                return ResourceManager.GetString("TxtPHColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Indicate skeleton color.
        /// </summary>
        public static string TxtPHColorEsq {
            get {
                return ResourceManager.GetString("TxtPHColorEsq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Indicate Body Condition.
        /// </summary>
        public static string TxtPHCondicion {
            get {
                return ResourceManager.GetString("TxtPHCondicion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Indicate Medical Diagnosis.
        /// </summary>
        public static string TxtPHDiagnostico {
            get {
                return ResourceManager.GetString("TxtPHDiagnostico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Indicate Sick Days.
        /// </summary>
        public static string TxtPHDiasEnfer {
            get {
                return ResourceManager.GetString("TxtPHDiasEnfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Indicate Age.
        /// </summary>
        public static string TxtPHEdad {
            get {
                return ResourceManager.GetString("TxtPHEdad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Indicate presence of edema.
        /// </summary>
        public static string TxtPHEdema {
            get {
                return ResourceManager.GetString("TxtPHEdema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Indicate performed euthanasia.
        /// </summary>
        public static string TxtPHEut {
            get {
                return ResourceManager.GetString("TxtPHEut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a indicate Date of Death.
        /// </summary>
        public static string TxtPHFecMue {
            get {
                return ResourceManager.GetString("TxtPHFecMue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Indicate Animal History.
        /// </summary>
        public static string TxtPHHistoria {
            get {
                return ResourceManager.GetString("TxtPHHistoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Indicate Place of Death.
        /// </summary>
        public static string TxtPHLugMue {
            get {
                return ResourceManager.GetString("TxtPHLugMue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Indicate Weight.
        /// </summary>
        public static string TxtPHPeso {
            get {
                return ResourceManager.GetString("TxtPHPeso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Indicate Signs Illness.
        /// </summary>
        public static string TxtPHSignos {
            get {
                return ResourceManager.GetString("TxtPHSignos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Indicate Treating often.
        /// </summary>
        public static string TxtPHTratamiento {
            get {
                return ResourceManager.GetString("TxtPHTratamiento", resourceCulture);
            }
        }
    }
}
