//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Necropsyology.Core.Recurso {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Recursos {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Recursos() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Necropsyology.Core.Recurso.Recursos", typeof(Recursos).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Access.
        /// </summary>
        public static string Acceso {
            get {
                return ResourceManager.GetString("Acceso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a About.
        /// </summary>
        public static string Acerca {
            get {
                return ResourceManager.GetString("Acerca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Simply the best animal necropsy app out there..
        /// </summary>
        public static string AcercaDetalle {
            get {
                return ResourceManager.GetString("AcercaDetalle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Download.
        /// </summary>
        public static string Descarga {
            get {
                return ResourceManager.GetString("Descarga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Introduction.
        /// </summary>
        public static string Intro {
            get {
                return ResourceManager.GetString("Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &amp;Refinements.
        /// </summary>
        public static string Mejoras {
            get {
                return ResourceManager.GetString("Mejoras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string Obt {
            get {
                return ResourceManager.GetString("Obt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Get app.
        /// </summary>
        public static string ObtenApp {
            get {
                return ResourceManager.GetString("ObtenApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pricing.
        /// </summary>
        public static string Precio {
            get {
                return ResourceManager.GetString("Precio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Great application that allows you to do everything you need..
        /// </summary>
        public static string Promo1 {
            get {
                return ResourceManager.GetString("Promo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sign Up.
        /// </summary>
        public static string Registro {
            get {
                return ResourceManager.GetString("Registro", resourceCulture);
            }
        }
    }
}
