//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Necropsyology.Core.Recurso {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RecursoNecropsia {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RecursoNecropsia() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Necropsyology.Core.Recurso.RecursoNecropsia", typeof(RecursoNecropsia).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Professional Certificate.
        /// </summary>
        public static string LblEtiCedMVZ {
            get {
                return ResourceManager.GetString("LblEtiCedMVZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Organization.
        /// </summary>
        public static string LblEtiDomOrg {
            get {
                return ResourceManager.GetString("LblEtiDomOrg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string LblEtiEmailMVZ {
            get {
                return ResourceManager.GetString("LblEtiEmailMVZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string LblEtiFecha {
            get {
                return ResourceManager.GetString("LblEtiFecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice.
        /// </summary>
        public static string LblEtiFolio {
            get {
                return ResourceManager.GetString("LblEtiFolio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Organization.
        /// </summary>
        public static string LblEtiMailOrg {
            get {
                return ResourceManager.GetString("LblEtiMailOrg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string LblEtiNomMVZ {
            get {
                return ResourceManager.GetString("LblEtiNomMVZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization Name.
        /// </summary>
        public static string LblEtiNomOrg {
            get {
                return ResourceManager.GetString("LblEtiNomOrg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization.
        /// </summary>
        public static string LblEtiOrg {
            get {
                return ResourceManager.GetString("LblEtiOrg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner Organization.
        /// </summary>
        public static string LblEtiPropOrg {
            get {
                return ResourceManager.GetString("LblEtiPropOrg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone.
        /// </summary>
        public static string LblEtiTelMVZ {
            get {
                return ResourceManager.GetString("LblEtiTelMVZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization Phone.
        /// </summary>
        public static string LblEtiTelOrg {
            get {
                return ResourceManager.GetString("LblEtiTelOrg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Necropsy Report.
        /// </summary>
        public static string LblHeaderTitulo {
            get {
                return ResourceManager.GetString("LblHeaderTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization Data.
        /// </summary>
        public static string LblTitDatGral {
            get {
                return ResourceManager.GetString("LblTitDatGral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MVZ information.
        /// </summary>
        public static string LblTitMVZ {
            get {
                return ResourceManager.GetString("LblTitMVZ", resourceCulture);
            }
        }
    }
}
