//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Necropsyology.Core.Recurso {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RecursoNecropsia {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RecursoNecropsia() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Necropsyology.Core.Recurso.RecursoNecropsia", typeof(RecursoNecropsia).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Professional Certificate.
        /// </summary>
        public static string LblEtiCedMVZ {
            get {
                return ResourceManager.GetString("LblEtiCedMVZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colour.
        /// </summary>
        public static string LblEtiColor {
            get {
                return ResourceManager.GetString("LblEtiColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body Condition.
        /// </summary>
        public static string LblEtiCond {
            get {
                return ResourceManager.GetString("LblEtiCond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clinical diagnosis.
        /// </summary>
        public static string LblEtiDiagnostico {
            get {
                return ResourceManager.GetString("LblEtiDiagnostico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sick Days.
        /// </summary>
        public static string LblEtiDiasEnfer {
            get {
                return ResourceManager.GetString("LblEtiDiasEnfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Organization.
        /// </summary>
        public static string LblEtiDomOrg {
            get {
                return ResourceManager.GetString("LblEtiDomOrg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age.
        /// </summary>
        public static string LblEtiEdad {
            get {
                return ResourceManager.GetString("LblEtiEdad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string LblEtiEmailMVZ {
            get {
                return ResourceManager.GetString("LblEtiEmailMVZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Species.
        /// </summary>
        public static string LblEtiEspecie {
            get {
                return ResourceManager.GetString("LblEtiEspecie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Euthanasia.
        /// </summary>
        public static string LblEtiEut {
            get {
                return ResourceManager.GetString("LblEtiEut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string LblEtiFecha {
            get {
                return ResourceManager.GetString("LblEtiFecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Death.
        /// </summary>
        public static string LblEtiFecMue {
            get {
                return ResourceManager.GetString("LblEtiFecMue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice.
        /// </summary>
        public static string LblEtiFolio {
            get {
                return ResourceManager.GetString("LblEtiFolio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animal History.
        /// </summary>
        public static string LblEtiHistoria {
            get {
                return ResourceManager.GetString("LblEtiHistoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animal Id.
        /// </summary>
        public static string LblEtiIdAnimal {
            get {
                return ResourceManager.GetString("LblEtiIdAnimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place of death.
        /// </summary>
        public static string LblEtiLugMue {
            get {
                return ResourceManager.GetString("LblEtiLugMue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string LblEtiMailOrg {
            get {
                return ResourceManager.GetString("LblEtiMailOrg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string LblEtiNomMVZ {
            get {
                return ResourceManager.GetString("LblEtiNomMVZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string LblEtiNomOrg {
            get {
                return ResourceManager.GetString("LblEtiNomOrg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization.
        /// </summary>
        public static string LblEtiOrg {
            get {
                return ResourceManager.GetString("LblEtiOrg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight.
        /// </summary>
        public static string LblEtiPeso {
            get {
                return ResourceManager.GetString("LblEtiPeso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner.
        /// </summary>
        public static string LblEtiPropOrg {
            get {
                return ResourceManager.GetString("LblEtiPropOrg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sex.
        /// </summary>
        public static string LblEtiSexo {
            get {
                return ResourceManager.GetString("LblEtiSexo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signs.
        /// </summary>
        public static string LblEtiSignos {
            get {
                return ResourceManager.GetString("LblEtiSignos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone.
        /// </summary>
        public static string LblEtiTelMVZ {
            get {
                return ResourceManager.GetString("LblEtiTelMVZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization Phone.
        /// </summary>
        public static string LblEtiTelOrg {
            get {
                return ResourceManager.GetString("LblEtiTelOrg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treatment.
        /// </summary>
        public static string LblEtiTratamiento {
            get {
                return ResourceManager.GetString("LblEtiTratamiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Necropsy Report.
        /// </summary>
        public static string LblHeaderTitulo {
            get {
                return ResourceManager.GetString("LblHeaderTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose one.
        /// </summary>
        public static string LblItemSel {
            get {
                return ResourceManager.GetString("LblItemSel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization Data.
        /// </summary>
        public static string LblTitDatGral {
            get {
                return ResourceManager.GetString("LblTitDatGral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disease Background.
        /// </summary>
        public static string LblTitHistoria {
            get {
                return ResourceManager.GetString("LblTitHistoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MVZ information.
        /// </summary>
        public static string LblTitMVZ {
            get {
                return ResourceManager.GetString("LblTitMVZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient Information.
        /// </summary>
        public static string LblTitPaciente {
            get {
                return ResourceManager.GetString("LblTitPaciente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicate Color.
        /// </summary>
        public static string TxtPHColor {
            get {
                return ResourceManager.GetString("TxtPHColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicate Body Condition.
        /// </summary>
        public static string TxtPHCondicion {
            get {
                return ResourceManager.GetString("TxtPHCondicion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicate Medical Diagnosis.
        /// </summary>
        public static string TxtPHDiagnostico {
            get {
                return ResourceManager.GetString("TxtPHDiagnostico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicate Sick Days.
        /// </summary>
        public static string TxtPHDiasEnfer {
            get {
                return ResourceManager.GetString("TxtPHDiasEnfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicate Age.
        /// </summary>
        public static string TxtPHEdad {
            get {
                return ResourceManager.GetString("TxtPHEdad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicate performed euthanasia.
        /// </summary>
        public static string TxtPHEut {
            get {
                return ResourceManager.GetString("TxtPHEut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to indicate Date of Death.
        /// </summary>
        public static string TxtPHFecMue {
            get {
                return ResourceManager.GetString("TxtPHFecMue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicate Animal History.
        /// </summary>
        public static string TxtPHHistoria {
            get {
                return ResourceManager.GetString("TxtPHHistoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicate Place of Death.
        /// </summary>
        public static string TxtPHLugMue {
            get {
                return ResourceManager.GetString("TxtPHLugMue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicate Weight.
        /// </summary>
        public static string TxtPHPeso {
            get {
                return ResourceManager.GetString("TxtPHPeso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicate Signs Illness.
        /// </summary>
        public static string TxtPHSignos {
            get {
                return ResourceManager.GetString("TxtPHSignos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicate Treating often.
        /// </summary>
        public static string TxtPHTratamiento {
            get {
                return ResourceManager.GetString("TxtPHTratamiento", resourceCulture);
            }
        }
    }
}
